### ISSUE TITLE
apply_fixes extremely slow

### ISSUE THREAD

**Issue by qq7te** [martis42/depend_on_what_you_use#217]
Hi, 
I'm experiencing incredibly long run times when I run the script that applies the fixes. 

I'm doing this on a single target, the actual `dwyu` run takes just a handful of seconds, and then I run `bazel run @depend_on_what_you_use//:apply_fixes -- --fix-all` and it runs for hours. I kid you not. Hours. 

Am I doing something wrong? Is it stuck on something but not telling me ? 
Do you have any tips for me so that I can provide more useful information without posting here my company's code ?  

Thanks!

**Comment by martis42** [comment]
Do I understand this correctly? You have a (presumably largish) workspace and execute the DWYU analysis on a single target. You did not use the recursive mode. So there really was only a single target analysed.

Then, you execute the apply_fixes script and it takes hours? This would indeed be quite unexpected.

Some questions:
- What platform are you running on?
- Is there any result after some hours? Or did you abort due to it taking forever?
- The script has options which allow you debugging `--dry-run` and `--verbose`. Do you see any output when using those?

The slowest thing the script does is performing bazel queries. They can be slowish under certain circumstances, but they should not take hours.
If the dry run option finishes fast, then try to execute the commands which the script would execute manually. This should help you understand the issue.

**Comment by qq7te** [comment]
Thank you for your super-prompt answer! 
Yes, I think your assumptions are spot-on. 
We have a massive workspace, but the analysis is on a single target.  The analysis is fast, the fixing is not.

I'm running on Linux:
Ubuntu 20.04, 
bazel 6.4.0, 
go 1.13

After a few hours (2 hours in the case of this last attempt I just made) I get a very nicely updated target in the BUILD file. 
I tried the dry-run option. Also 2 hours.  
We're talking about a workstation with 16 cores, AMD Ryzen Threadripper PRO 3955WX , with 64 GB of RAM.
It's weird.

It works, it's great... but I just don't know why it's taking so long :) 
is there a debug mode that would help me understand what it's doing for so long, or a way to log its actions or profile it ?

**Comment by martis42** [comment]
Given what you describe it is really most likely that the queries take so long. The buildozer step to adapt the BUILD files cannot be problematic if the dry run takes also long.

I assume in your case you want to add missing dependencies, correct?

Can you please perform the following tests:

1)
Execute with `--fix-unused-deps` (and `--fix-deps-which-should-be-private` if this does apply to you) instead of `--fix-all`. I expect this runs quite fast.
If it does not run fast, please add `--verbose` and tell me what you can observe.

2)
Assuming 1) is fast. Please run the slow command with `--verbose`. I expect that some queries will be printed. Are it many queries spamming your terminal, or few queries taking quite long (long means > 1 minute)?
If it are single long running queries. Please copy the command and execute them yourself. Does this show why they take so long?

**Comment by qq7te** [comment]
... lots of digging later... 

I ran the same command on an identical machine, with the same project checked out and it took less than a second to run.

It took me a while to find out why.

I noticed that on my original machine, no output was displayed, and every time I would cancel execution, the code would be stuck in `bazel_bin.glob('**/*')` in `apply_fix.py`   (line 61)

As it turns out, on the other machine (the fast one), I didn't make a full build and recently cleared my builds. 
There were `24MB` of data, and `180` files

On my initial machine (the slow one) I had `298GB` of data, and `147733` files

I think I now understand the problem.  Unless I have a fairly clean bazel-bin , that glob will take forever

**Comment by martis42** [comment]
Thanks for the detailed feedback and analysis. I did indeed not foresee workspaces being so large that finding the report files becomes a bottleneck :laughing: 

Could you tell me which Python version you are using.

I will look into this, if can speed this up a but. In the end searching the report files will always scale with the workspace files. But still, 2 h is too long for the numbers you presented. Maybe my glob usage is a slow and bad anti pattern.

I believe I can help you in the meantime with a workaround. The `--bazel-bin` option of the fixes script allows you to specify at which directory the script searches recursively for the report files. This does not actually have to be the root of a bazel-bin directory tree, but can actually be any sub tree in your bazel-out. While using this is a bit clunky, you can restrict the search scope like this and sped things up.

**Comment by martis42** [comment]
I tried to reproduce your issue, but failed doing so. My test setup included 25 million empty files evenly distributed in a directory structure 100 directories "wide" and 500 levels "deep". In this scenario the `bazel_bin.glob('**/*')` required ~ 50 seconds. Given what the glob does, I don't expect file size to matter. Maybe symlinks are a major slowdown or there are other fundamental differences between our systems.

That much said, I tinkered around with different implementations for searching for files. It turns out a solution based on `os.walk` requires roundabout half the time of the pathlib based solution. Thus, https://github.com/martis42/depend_on_what_you_use/pull/221 should reduce the pain in this case at least a bit. `os.walk` also requires far less RAM, so this is an additional bonus.

Unfortunately, I don't have a proper solution for the extreme slowness you describe, besides limiting the search scope by manually telling the script where to look for report files. I renamed the corresponding CLI option to make it more obvious in the help, that it can be used like that.

**Comment by qq7te** [comment]
Thanks @martis42 , that's probably the most effective help I can get. 
I don't know what about my filesystem is making the globbing slow, but between the changes you made and the ability to narrow the search, this is definitely going to help. 

Thank you for the short turnaround!  I'm ok with closing this.  
If I find out more about my filesystem that can be a hint of a more common problem, I'll let you know!

**Comment by martis42** [comment]
@qq7te The fix is now officially released. Beware, version 0.1.0 has some breaking changes. Nothing major though.

**Comment by martis42** [comment]
@qq7te In case you still see those issues. Release 0.3.0 provides an alternative workflow, which hopefully helps your use case (aka "DWYU aspect execution is fast, but discovering the DWYU reports is slow")
