### ISSUE TITLE
Automatic Fixes: bazel compilation-mode was not respected.

### ISSUE THREAD

**Issue by storypku** [martis42/depend_on_what_you_use#39]
If we first run `bazel build -c opt --config=dwyu //somepath/...` then followed by a `bazel run -c opt @depend_on_what_you_use//:apply_fixes -- --workspace=/path/to/my/project`, apply fixes won't try to glob `xxx_dwyu_report.json` files under the actual `bazel-bin` directory:

```
ls -ld bazel-bin
lrwxrwxrwx 1 story story 93 May  8 17:30 bazel-bin -> /home/story/.cache/bazel/5f6cfd791ed6436cd7d0a9ad06515f99/execroot/com_qcraft/bazel-out/k8-opt/bin
```
shows that it was symlinked to some `xxx/k8-opt/bin` directory

However,  the directory from running `bazel info bazel-bin` was `xxx/k8-fastbuild/bin` (See below). 

```
$ bazel info bazel-bin
/home/story/.cache/bazel/5f6cfd791ed6436cd7d0a9ad06515f99/execroot/com_qcraft/bazel-out/k8-fastbuild/bin
```

Shall we use `readlink bazel-bin` rather than `bazel info bazel-bin` to locate the actual `bazel-bin` directory ?

**Comment by martis42** [comment]
The straight forward solution is to drop `-c opt` from the build command for running the aspect. The `--compilation-mode` option has has no influence on the aspect besides changing which `bazel-out` sub directory is being used.
DWYU is a static analyzer which does not execute any compilation action.

I see however, how one can easily stumble into this pitfall. The compilation mode could be hidden behind a config or set in a `.bazelrc` file, making the problem potentially hard to understand. Or one simply uses the compilation mode out of habit because it is relevant for all the normal build commands one executes regularly. 

Regarding your proposed solution.
I am not in favor of the `readlinks` approach:
* It reduces the portability of DWYU. The `readlinks` tool is not available on all common platforms.
* The convenience symlinks into `bazel-out` are not stable.
  * One can control they are created / updated at all through the flag [--experimental_convenience_symlinks](https://docs.bazel.build/versions/main/command-line-reference.html#flag--experimental_convenience_symlinks).
  * Users can change the name of those symlinks via [--symlink_prefix](https://docs.bazel.build/versions/main/command-line-reference.html#flag--symlink_prefix).

As said above I do understand that this is a pitfall and it should be mitigated.
My proposal are the following steps:
1. Extend the documentation to mention explicitly that no compilation mode has to be specified for using DWYU.
1. Offer a CLI flag for the `apply_fixes` tool for providing a path directly to the `bazel-out` path which should be used by the tool. While this is not very convenient for the user, it offers maximum flexibility for all cases where for whatever reason DWYU was not used with `fastbuild`. This would also be a solution for cases where users do use multiple output bases via [--output_base](https://docs.bazel.build/versions/main/command-line-reference.html#flag--output_base).
1. The `apply_fixes` tool should return with an error if no DWYU report files can be discovered. Printing a warning about the most likely causes: "Did not run DWYU beforehand" or "Mixed up compilation mode / output base". This should make it less likely that the tool silently does nothing and the user is surprised by no problem being fixed.

Would those mitigations work for you?

**Comment by storypku** [comment]
If portability is a concern, I agree that readlink is not a good idea. And I agree with your ideas to mitigate this pitfall. 
I would like to mention that, currently, if we run two `apply_fixes` consecutively without re-running DWYU in between, the later would probably fail since we didn't remove/"consume" existing DWYU reports after the fix. Maybe we can file another issue to discuss this situation.

**Comment by martis42** [comment]
I am closing this issue. With https://github.com/martis42/depend_on_what_you_use/pull/47 most reported points should be mitigated.

I changed my opinion regarding your initial request. Creating the convenience symlinks at the workspace root is the default Bazel behavior and thus it makes sense that the `apply_fixes` default behavior depends on it.

There have been several changes:
- One no longer has to provide `--workspace` if one invokes `apply_fixes` from the target workspace. The workspace root is deduced automatically.
- The output directory is deduced by following the `bazel-bin` convenience symlink.
- Alternative options for discovering the output directory are available, see the help.

@storypku 
It would be great if you could test the latest `apply_fixes` version. Is it now behaving in a convenient manner?
