### ISSUE TITLE
DWYU and gRPC

### ISSUE THREAD

**Issue by storypku** [martis42/depend_on_what_you_use#40]
## Problem Description
Running DWYU on `cc_grpc_library` targets will fail with errmsg like below:

```
DWYU analyzing: '//proto:hello_world_cc_grpc'
Result: FAILURE
Includes which are not available from the direct dependencies:
  File='bazel-out/k8-fastbuild/bin/proto/hello_world.grpc.pb.h', include='grpcpp/impl/codegen/client_callback.h'
  File='bazel-out/k8-fastbuild/bin/proto/hello_world.grpc.pb.h', include='grpcpp/impl/codegen/message_allocator.h'
  File='bazel-out/k8-fastbuild/bin/proto/hello_world.grpc.pb.h', include='grpcpp/impl/codegen/server_context.h'
  File='bazel-out/k8-fastbuild/bin/proto/hello_world.grpc.pb.h', include='grpcpp/impl/codegen/method_handler.h'
  File='bazel-out/k8-fastbuild/bin/proto/hello_world.grpc.pb.h', include='grpcpp/impl/codegen/status.h'
```
See https://github.com/storypku/dwyu_grpc_demo.git, which was created to illestrate this issue. 

## Analysis

From DWYU's perspective, this issue was due to the missing direct dependency of `@com_github_grpc_grpc//:grpc++_codegen_base`. In fact, if `@com_github_grpc_grpc//:grpc++_codegen_base` was added to `deps` of `//proto:hello_world_cc_proto`, running DWYU will succeed.

However, since the `cc_grpc_library` rule was provided by gRPC, making changes to `cc_grpc_library` rule implementation seems a better solution for issues like this.

BTW, I have tried either adding `grpcpp/impl/codegen` stuff to DWYU's ignore headers list, or simply tagged `cc_grpc_library` targets as `"no-dwyu"`, neither of them seems a good workaround.

## Discussion Time
My question is, should we workaround this within DWYU or file an PR for upstream gRPC?

**Comment by martis42** [comment]
Regarding your discussion point, my answer is we should do both.

If this rule violates the DWYU design principle and we believe in this design being a good one, an upstream change request sounds like a good step forward.

That much said, there will always be some libraries/rules outside our control. Or maybe it is simply out of scope for a project to adapt upstream sources due to budget and/or time constraints.
Thus, DWYU should offer efficient mechanisms for providing allow lists.
Meaning, I would like to understand why ignoring the headers does not work. Maybe we even require a separate mechanism to ignore a specific set of targets.

**Comment by storypku** [comment]
> Meaning, I would like to understand why ignoring the headers does not work. Maybe we even require a separate mechanism to ignore a specific set of targets.

Ignoring the list of "grpcpp/impl/codegen/xxx.h" do work in this case. However, maintaining such a long ignore list is a maintanance burden if we later decided to bump to a higher gRPC version and this ignore list changed.

**Comment by martis42** [comment]
The straight forward approach would be to support regex patterns for to be ignored headers. This would reduce the maintenance burden for longish header lists.

The alternative is to introduce the possibility to list targets whose headers shall be ignored. Implementing this is however not as straight forward as simply adding regex support.

**Comment by martis42** [comment]
I am closing this issue.

It is now possible to ignore headers by providing regex patterns. This should ease maintaining the list of headers which are to be ignored by DWYU checks.

Establishing such an allow list based on targets would be less robust. The aspect might not be able to depend on targets which shall be filtered, due to visibility constraints.

Feel free to reopen the issue or create a new one if the header filtering based on patterns is not sufficient to efficiently maintain the header ignore list.
